name: Convert Mardown to target formats
on: [push]
env:
  book_name: book
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build EPUB
        uses: addnab/docker-run-action@v3
        with:
          image: pandoc/latex:latest
          options: -v ${{ github.workspace }}:/data
          run: -o ${{ env.book_name }}.epub -s $(find . -maxdepth 1 -mindepth 1 -name \*.md -a -not -name README.md | sort)
      - name: Build DOCX
        uses: addnab/docker-run-action@v3
        with:
          image: pandoc/latex:latest
          options: -v ${{ github.workspace }}:/data
          run: --toc -o ${{ env.book_name }}.docx -s $(find . -maxdepth 1 -mindepth 1 -name \*.md -a -not -name README.md | sort)
      - name: Upload EPUB
        uses: actions/upload-artifact@v3
        with:
          name: EPUB
          path: ${{ env.book_name }}.epub
          if-no-files-found: error
      - name: Upload DOCX
        uses: actions/upload-artifact@v3
        with:
          name: DOCX
          path: ${{ env.book_name }}.docx
          if-no-files-found: error
